language: node_js
node_js:
  - '8'
dist: trusty
branches:
  only:
    - master
addons:
  chrome: stable
install:
  - npm install
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start -ac -screen 0 1280x1024x16"
  - sleep 3 # give xvfb some time to start
script:
  - npm test
