language: node_js
node_js:
  - '8'
dist: trusty
branches:
  only:
    - master
addons:
  apt:
    packages:
      - xvfb
  chrome: stable
install:
  - npm install
before_script:
  - export DISPLAY=':99.0'
script:
  - xvfb-run npm test
